### ISSUE TITLE
关于英文摘要那一页论文名称的情况

### ISSUE THREAD

**Issue by Explorerk** [JChrysanthemum/LZUThesis2020-PgD-PhD#1]

**Comment by Explorerk** [comment]
这个问题已经解决了，这个可以手动修改，遇到另一个问题是编写出来的公式看上去很丑，尤其是求和符号等等
![image](https://user-images.githubusercontent.com/21061830/103986536-e35f1a80-51c5-11eb-85ac-ba4503d68061.png)

**Comment by fengyongkang** [comment]
参考文献的格式里面怎么加入超链接到文章网站的呀
